---
- name: config | Mounting NFS Exports for ALL
  mount:
    fstype: "{{ item['fstype'] }}"
    opts: "{{ (item['opts']|join(','))|default(omit) }}"
    path: "{{ item['path'] }}"
    src: "{{ item['src'] }}"
    state: "{{ item['state'] }}"
  become: true
  with_items: '{{ nfs_client_mounts_all }}'
  when: nfs_client_mounts_all is defined

- name: config | Mounting NFS Exports for GROUP
  mount:
    fstype: "{{ item['fstype'] }}"
    opts: "{{ (item['opts']|join(','))|default(omit) }}"
    path: "{{ item['path'] }}"
    src: "{{ item['src'] }}"
    state: "{{ item['state'] }}"
  become: true
  with_items: '{{ nfs_client_mounts_group }}'
  when: nfs_client_mounts_group is defined

- name: config | Mounting NFS Exports for HOST
  mount:
    fstype: "{{ item['fstype'] }}"
    opts: "{{ (item['opts']|join(','))|default(omit) }}"
    path: "{{ item['path'] }}"
    src: "{{ item['src'] }}"
    state: "{{ item['state'] }}"
  become: true
  with_items: '{{ nfs_client_mounts_host }}'
  when: nfs_client_mounts_host is defined
